version: 0.2

 

phases:

  install:

    commands:

      - echo "No dependencies to install for HTML site"

  pre_build:

    commands:

      - echo "Starting build"

  build:

    commands:

      - echo "Build completed"

  post_build:

    commands:

      - echo "Deploying to S3"

      # Sync the local directory (with built files) to the S3 bucket

      - aws s3 sync . s3://helenzys-demo --delete

 

artifacts:

  files:

    - '**/*'

  discard-paths: yes
